### ISSUE TITLE
Deserializing of enum that was transformed in their string representation fails

### ISSUE THREAD

**Issue by Brilbroeder** [vpekarek/InterfaceConverter.SystemTextJson#1]
In ConfigureServices

         services
                .AddJsonOptions(options =>
                {
                    if (options.JsonSerializerOptions != null)
                    {
                        options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter(JsonNamingPolicy.CamelCase));
                    }
                });

Class / Interfaces Decorate with your Attribute and with enum fail to deserialize if this is turned on.

**Comment by vpekarek** [comment]
Hi @Brilbroeder . Thank you for your feedback. Can you provide a code sample? I tried it in the template .NET App project and works fine. 
**Program.cs**:

```
using System.Text.Json.Serialization;
using System.Text.Json;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddRazorPages();
builder.Services.AddControllers().AddJsonOptions(options =>
{
    options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter(JsonNamingPolicy.CamelCase));
});

var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();

app.UseRouting();

app.UseAuthorization();

app.MapRazorPages();
app.MapControllers();

app.Run();

```

**ExampleController.cs**:

```
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace TestApp;

[ApiController]
[Route("[controller]")]
public class ExampleController : ControllerBase
{
    [HttpGet("/example")]
    public IActionResult Test([FromQuery] RequestData data)
    {
        return Ok(data);
    }
}

public enum CustomType
{
    FirstType,
    SecondType,
    ThirdType
}

public class RequestData : IDataWithEnum
{
    [FromQuery]
    public string Name { get; set; }

    [FromQuery]
    public CustomType MyType { get; set; }
}

[JsonInterfaceConverter(typeof(InterfaceWriteConverter<IDataWithEnum>))]
public interface IDataWithEnum
{
    string Name { get; set; }
    CustomType MyType { get; set; }
}
```

When I call the `example?name=Test&MyType=2` or `example?name=Test&MyType=secondType` endpoint, the data is serialized correctly.

**Comment by Brilbroeder** [comment]
Ok. I'll try to create a sample project to reproduce it.

**Comment by Brilbroeder** [comment]
Your sample is with a Get / FromQuery string. The case I ran into was most likely a POST and data in JSON body.

**Comment by vpekarek** [comment]
Hi @Brilbroeder 
The sample project will be great. I did some tests with POST and JSON body and did not run to any error, but there should be something different in the configuration that cause the problem.

**Comment by vpekarek** [comment]
Can't reproduce the problem.
