### ISSUE TITLE
Add support for netstandard 2.0

### ISSUE THREAD

**Issue by StefH** [vpekarek/InterfaceConverter.SystemTextJson#2]
Can you please make your NuGet multi target and include netstandard 2.0?

``` xml
<TargetFrameworks>netstandard2.0;net6.0</TargetFrameworks>
```

**Comment by vpekarek** [comment]
Hello. Thank you for your hint. The [new version](https://www.nuget.org/packages/InterfaceConverter.SystemTextJson/1.2.0) is available with support for netstandard 2.0.

**Comment by StefH** [comment]
Thank you for the quick solution !
